'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ejs = require('ejs');
const aulaModel = require('../models/aulaModel');
const { crearControlador, obtenerDatos, validarDatos } = require('../controllers/adminAulaController');
const crearMenuAdmin = require('../config/adminMenu');
const { requireRole } = require('../middlewares/authMiddleware');
const root = path.join(__dirname, '..');
const leer = (ruta) => fs.readFileSync(path.join(root, ruta), 'utf8');
const res = () => ({ statusCode: 200, body: null, view: null, locals: null, redirectTo: null, status(c) { this.statusCode = c; return this; }, send(x) { this.body = x; return this; }, render(v, d) { this.view = v; this.locals = d; return this; }, redirect(x) { this.redirectTo = x; return this; } });
const req = (extra = {}) => ({ params: {}, query: {}, body: {}, session: { usuario: { id: 1, rol: 'ADMINISTRADOR' } }, ...extra });

test('01 listado autorizado conserva filtros y paginación', async () => { let filtros; const r = res(); await crearControlador({ contarFiltradas: async f => { filtros = f; return 1; }, listarPaginado: async () => [{ id: 1 }] }).listar(req({ query: { q: ' LAB ', estado: 'activo', pagina: '1' } }), r); assert.equal(r.view, 'admin/aulas/index'); assert.deepEqual(filtros, { busqueda: 'LAB', activo: true }); });
test('02 sin sesión redirige a login', () => { const r = res(); requireRole('ADMINISTRADOR')({ session: {}, originalUrl: '/admin/aulas' }, r, () => {}); assert.equal(r.redirectTo, '/login'); });
test('03 otro rol conserva redirección', () => { const r = res(); requireRole('ADMINISTRADOR')({ session: { usuario: { rol: 'DOCENTE' } }, originalUrl: '/admin/aulas' }, r, () => {}); assert.equal(r.redirectTo, '/dashboard/docente'); });
test('04 GET nueva responde 200', () => { const r = res(); crearControlador({}).mostrarNueva(req(), r); assert.equal(r.statusCode, 200); assert.equal(r.view, 'admin/aulas/nuevo'); });
test('05 POST está cubierto por CSRF global', () => { const app = leer('index.js'); assert.ok(app.indexOf('app.use(csrfProtection)') < app.indexOf("app.use('/admin/aulas'")); assert.match(leer('middlewares/csrfMiddleware.js'), /status\(403\)/); });
test('06 creación normaliza clave fuerza activo y usa NULL', async () => { let dato; const r = res(); await crearControlador({ buscarDuplicadoClave: async () => null, crear: async d => { dato = d; } }).crear(req({ body: { clave: ' aula_3 ', nombre: ' Aula tres ', descripcion: '', activo: '0' } }), r); assert.deepEqual(dato, { clave: 'AULA_3', nombre: 'Aula tres', descripcion: null, activo: true }); assert.equal(r.redirectTo, '/admin/aulas?creado=1'); });
test('07 clave vacía o larga da 422', async () => { for (const clave of [' ', 'X'.repeat(31)]) { const r = res(); await crearControlador({}).crear(req({ body: { clave, nombre: 'Aula' } }), r); assert.equal(r.statusCode, 422); } });
test('08 nombre corto o largo da 422', async () => { for (const nombre of ['X', 'X'.repeat(151)]) { const r = res(); await crearControlador({}).crear(req({ body: { clave: 'A', nombre } }), r); assert.equal(r.statusCode, 422); } });
test('09 descripción mayor de 500 se rechaza', () => assert.match(validarDatos(obtenerDatos({ clave: 'A', nombre: 'Aula', descripcion: 'x'.repeat(501) })), /500/));
test('10 controles se rechazan', () => assert.match(validarDatos(obtenerDatos({ clave: 'A\u0000B', nombre: 'Aula' })), /control/));
test('11 duplicado devuelve 422 seguro', async () => { const r = res(); await crearControlador({ buscarDuplicadoClave: async () => ({ id: 2 }) }).crear(req({ body: { clave: 'A', nombre: 'Aula' } }), r); assert.equal(r.statusCode, 422); assert.doesNotMatch(r.locals.error, /SQL|ER_DUP/i); });
test('12 edición válida excluye su ID del duplicado', async () => { let excluir; const r = res(); await crearControlador({ buscarPorId: async () => ({}), buscarDuplicadoClave: async (c, id) => { excluir = id; return null; }, actualizar: async () => ({ affectedRows: 1 }) }).actualizar(req({ params: { id: '2' }, body: { clave: 'lab_2', nombre: 'Laboratorio' } }), r); assert.equal(excluir, 2); assert.equal(r.redirectTo, '/admin/aulas?actualizado=1'); });
test('13 aula inexistente devuelve 404', async () => { const r = res(); await crearControlador({ buscarPorId: async () => null }).actualizar(req({ params: { id: '3' }, body: { clave: 'A', nombre: 'Aula' } }), r); assert.equal(r.statusCode, 404); });
test('14 estado cambia mediante método específico', async () => { let valor; const r = res(); await crearControlador({ buscarPorId: async () => ({ activo: 1 }), actualizarEstado: async (id, activo) => { valor = activo; return { affectedRows: 1 }; } }).actualizarEstado(req({ params: { id: '1' }, body: { accion: 'desactivar' } }), r); assert.equal(valor, false); });
test('15 estado idempotente no escribe', async () => { let n = 0; const r = res(); await crearControlador({ buscarPorId: async () => ({ activo: 1 }), actualizarEstado: async () => { n += 1; } }).actualizarEstado(req({ params: { id: '1' }, body: { accion: 'activar' } }), r); assert.equal(n, 0); });
test('16 affectedRows cero produce 404', async () => { const r = res(); await crearControlador({ buscarPorId: async () => ({}), buscarDuplicadoClave: async () => null, actualizar: async () => ({ affectedRows: 0 }) }).actualizar(req({ params: { id: '1' }, body: { clave: 'A', nombre: 'Aula' } }), r); assert.equal(r.statusCode, 404); });
test('17 LIKE usa placeholders y límite seguro', () => { const c = aulaModel.construirCondicionesListado({ busqueda: "A%'_", activo: false }); assert.equal(c.parametros.length, 3); assert.match(c.clausulaWhere, /LIKE \?/); assert.doesNotMatch(c.clausulaWhere, /A%/); assert.match(leer('models/aulaModel.js'), /limite > 0 && limite <= 50/); });
test('18 error MySQL se sanea como 503', async () => { const r = res(); await crearControlador({ contarFiltradas: async () => { throw new Error('SQL privado'); } }).listar(req(), r); assert.equal(r.statusCode, 503); assert.doesNotMatch(r.body, /SQL privado/); });
test('19 EJS escapa valores', () => { const file = path.join(root, 'views/admin/aulas/nuevo.ejs'); const html = ejs.render(leer('views/admin/aulas/nuevo.ejs'), { title: 'x', menuItems: [], csrfToken: 't', error: null, datos: { clave: '<x>', nombre: '<y>', descripcion: '<z>' } }, { filename: file }); assert.match(html, /&lt;x&gt;/); assert.doesNotMatch(html, /value="<x>"/); });
test('20 no existe DELETE', () => { assert.doesNotMatch(leer('routes/adminAulaRoutes.js'), /router\.delete/i); assert.doesNotMatch(leer('models/aulaModel.js'), /DELETE\s+FROM/i); });
test('21 formularios no aceptan activo', () => { assert.equal(Object.hasOwn(obtenerDatos({ clave: 'A', nombre: 'Aula', activo: '0' }), 'activo'), false); assert.doesNotMatch(leer('views/admin/aulas/nuevo.ejs') + leer('views/admin/aulas/editar.ejs'), /name="activo"/); });
test('22 menú Aulas sigue a Materias y queda activo', () => { const menu = crearMenuAdmin('aulas'); const aulas = menu.findIndex(x => x.texto === 'Aulas'); assert.equal(menu[aulas].url, '/admin/aulas'); assert.equal(menu[aulas].activo, true); assert.equal(menu[aulas - 1].texto, 'Materias'); });
test('23 rutas están protegidas y nuevo precede a dinámicas', () => { const rutas = leer('routes/adminAulaRoutes.js'); assert.ok(rutas.indexOf("router.get('/nuevo'") < rutas.indexOf("router.get('/:id/editar'")); assert.match(rutas, /requireAuth/); assert.match(rutas, /requireRole\('ADMINISTRADOR'\)/); });
