'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const manifestApi = require('../scripts/migrationManifest');
const apply = require('../scripts/migrationApply');

const manifest = manifestApi.cargarManifiesto();
const entry = manifest.migraciones.find((item) => item.version === 16);
const sqlPath = path.join(manifestApi.MIGRATIONS_DIR, entry.archivo);
const sql = fs.readFileSync(sqlPath, 'utf8');
const contract = apply.cargarContrato(entry);
const normalized = sql.replace(/\s+/g, ' ').trim();
const executable = apply.separarSentenciasSql(sql).join('\n');

test('01 archivo 016 existe y esta ACTIVE', () => { assert.ok(fs.statSync(sqlPath).isFile()); assert.equal(entry.estado, 'ACTIVE'); });
test('02 checksum SQL coincide', () => assert.equal(manifestApi.calcularChecksumCanonico(sqlPath), entry.checksumSha256));
test('03 contiene un unico ALTER TABLE grupos', () => { assert.equal((executable.match(/\bALTER\s+TABLE\b/gi) || []).length, 1); assert.match(executable, /ALTER TABLE grupos/i); });
test('04 runner clasifica ALTER declarado', () => assert.deepEqual(apply.validarSqlMigracion(entry).map(({ operation, target }) => ({ operation, target })), [{ operation: 'ALTER_TABLE', target: 'grupos' }]));
test('05 generacion_id es INT UNSIGNED nullable', () => assert.match(normalized, /ADD COLUMN generacion_id INT UNSIGNED NULL/i));
test('06 periodo_academico_id es INT UNSIGNED nullable', () => assert.match(normalized, /ADD COLUMN periodo_academico_id INT UNSIGNED NULL/i));
test('07 no hay defaults artificiales', () => assert.doesNotMatch(normalized, /generacion_id[^,]*DEFAULT|periodo_academico_id[^,]*DEFAULT/i));
test('08 define exactamente dos indices', () => assert.equal((sql.match(/\bADD\s+(?:KEY|INDEX)\b/gi) || []).length, 2));
test('09 indices tienen nombres y columnas correctos', () => { assert.match(normalized, /idx_grupos_generacion_id \(generacion_id\)/i); assert.match(normalized, /idx_grupos_periodo_academico_id \(periodo_academico_id\)/i); });
test('10 define exactamente dos FK', () => assert.equal((sql.match(/\bFOREIGN\s+KEY\b/gi) || []).length, 2));
test('11 FK de generacion es correcta', () => assert.match(normalized, /FOREIGN KEY \(generacion_id\) REFERENCES generaciones \(id\)/i));
test('12 FK de periodo es correcta', () => assert.match(normalized, /FOREIGN KEY \(periodo_academico_id\) REFERENCES periodos_academicos \(id\)/i));
test('13 ambas FK usan ON UPDATE CASCADE', () => assert.equal((sql.match(/ON\s+UPDATE\s+CASCADE/gi) || []).length, 2));
test('14 ambas FK usan ON DELETE RESTRICT', () => assert.equal((sql.match(/ON\s+DELETE\s+RESTRICT/gi) || []).length, 2));
test('15 no usa ON DELETE CASCADE', () => assert.doesNotMatch(sql, /ON\s+DELETE\s+CASCADE/i));
test('16 no contiene DML', () => assert.doesNotMatch(executable, /^\s*(?:INSERT|UPDATE|DELETE|REPLACE)\b/im));
test('17 no contiene DROP CREATE ni TRUNCATE', () => assert.doesNotMatch(sql, /\b(?:DROP|CREATE|TRUNCATE)\b/i));
test('18 no contiene ENUM triggers ni rutinas', () => assert.doesNotMatch(sql, /\b(?:ENUM|TRIGGER|PROCEDURE|FUNCTION|EVENT)\b/i));
test('19 no altera ciclo_escolar heredado', () => assert.doesNotMatch(normalized, /(?:MODIFY|CHANGE|DROP|RENAME)\s+(?:COLUMN\s+)?ciclo_escolar/i));
test('20 no agrega ciclo_escolar_id redundante', () => assert.doesNotMatch(sql, /\bciclo_escolar_id\b/i));
test('21 no agrega columnas sustituidas', () => assert.doesNotMatch(sql, /\b(?:docente_id|orientador_id|periodo_semestre)\b/i));
test('22 no agrega generacion textual', () => assert.doesNotMatch(sql, /ADD\s+COLUMN\s+generacion\s/i));
test('23 no inserta datos de catalogo', () => assert.doesNotMatch(sql, /\bINSERT\b/i));
test('24 contrato corresponde a 016', () => { assert.equal(contract.migracion, 16); assert.equal(contract.identificador, '016'); });
test('25 checksum del contrato coincide', () => assert.equal(manifestApi.calcularChecksumCanonico(path.join(manifestApi.PROJECT_ROOT, entry.execution.postconditionContract)), entry.execution.postconditionChecksumSha256));
test('26 contrato limita su alcance a grupos', () => assert.deepEqual(Object.keys(contract.tablas), ['grupos']));
test('27 contrato conserva ciclo_escolar varchar 20', () => assert.ok(contract.tablas.grupos.columnas.some((c) => c.nombre === 'ciclo_escolar' && c.tipo === 'varchar(20)' && !c.nullable)));
test('28 contrato exige referencias nullable compatibles', () => { for (const name of ['generacion_id', 'periodo_academico_id']) assert.ok(contract.tablas.grupos.columnas.some((c) => c.nombre === name && c.tipo === 'int unsigned' && c.unsigned && c.nullable)); });
test('29 contrato exige los dos indices', () => { for (const name of ['generacion_id', 'periodo_academico_id']) assert.ok(contract.tablas.grupos.indices.some((i) => i.columnas.length === 1 && i.columnas[0] === name)); });
test('30 contrato exige las dos FK seguras', () => { const fks = contract.tablas.grupos.foreignKeys.filter((fk) => ['generacion_id', 'periodo_academico_id'].includes(fk.columnas[0])); assert.equal(fks.length, 2); assert.ok(fks.every((fk) => fk.onDelete === 'RESTRICT' && fk.onUpdate === 'CASCADE')); });
test('31 contrato prohíbe columnas sustituidas', () => assert.deepEqual(contract.columnasProhibidas.grupos, ['docente_id', 'orientador_id', 'generacion', 'periodo_semestre', 'ciclo_escolar_id']));
test('32 contrato declara invariantes de datos', () => assert.deepEqual(contract.invariantesDatos, ['GROUP_COUNT_UNCHANGED', 'LEGACY_GROUP_VALUES_UNCHANGED', 'NEW_GROUP_REFERENCES_NULL_FOR_EXISTING_ROWS']));
test('33 manifiesto depende de 015', () => assert.deepEqual(entry.execution.dependsOn, [15]));
test('34 precondiciones cubren tablas y columnas', () => { const types = entry.execution.preconditions.map((p) => p.type); assert.ok(types.includes('MIGRATION_APPLIED')); assert.ok(types.includes('TABLE_PRESENT')); assert.equal(types.filter((t) => t === 'COLUMN_ABSENT').length, 2); });
test('35 precondiciones cubren indices y FK ausentes', () => { const types = entry.execution.preconditions.map((p) => p.type); assert.equal(types.filter((t) => t === 'INDEX_ABSENT').length, 2); assert.equal(types.filter((t) => t === 'FOREIGN_KEY_ABSENT').length, 2); });
test('36 precondiciones preservan contrato heredado', () => { const matches = entry.execution.preconditions.filter((p) => p.type === 'COLUMN_MATCH'); assert.deepEqual(matches.map((p) => p.target), ['id', 'ciclo_escolar']); });
test('37 017 a 019 ACTIVE; 020 a 021 siguen PLANNED', () => { for (const version of [17, 18, 19]) assert.equal(manifest.migraciones.find((m) => m.version === version).estado, 'ACTIVE'); for (let version = 20; version <= 21; version += 1) assert.equal(manifest.migraciones.find((m) => m.version === version).estado, 'PLANNED'); });
test('38 estados heredados permanecen protegidos', () => { assert.equal(manifest.migraciones.find((m) => m.version === 10).estado, 'RESERVED_MISSING'); for (const version of [9, 11, 12, 13, 14]) assert.equal(manifest.migraciones.find((m) => m.version === version).estado, 'SUPERSEDED_NOT_APPLIED'); });
