const cicloModel = require('../models/cicloEscolarModel');
const h = require('./adminAcademicCalendarShared');
const vacios = { clave: '', nombre: '', fechaInicio: '', fechaFin: '' };
const obtenerDatos = (b = {}) => ({ clave: h.normalizarTexto(b.clave).toLocaleUpperCase('es-MX'), nombre: h.normalizarTexto(b.nombre), fechaInicio: h.normalizarTexto(b.fecha_inicio), fechaFin: h.normalizarTexto(b.fecha_fin) });
const validarDatos = (d) => { if (!d.clave || d.clave.length > 30) return 'La clave debe contener entre 1 y 30 caracteres.'; if (!d.nombre || d.nombre.length > 100) return 'El nombre debe contener entre 1 y 100 caracteres.'; if ([d.clave, d.nombre].some(h.contieneControl)) return 'Los textos no pueden contener caracteres de control.'; if (!h.fechaValida(d.fechaInicio) || !h.fechaValida(d.fechaFin)) return 'Las fechas no son válidas.'; if (d.fechaInicio > d.fechaFin) return 'La fecha final no puede ser anterior a la inicial.'; return null; };
const crearControlador = (modelo = cicloModel) => {
 const render = (res, vista, o = {}) => res.status(o.status || 200).render(`admin/ciclos-escolares/${vista}`, { title: `${vista === 'nuevo' ? 'Registrar' : 'Editar'} ciclo escolar | COBAEM 30`, menuItems: h.menuCalendario(), error: o.error || null, datos: o.datos || vacios });
 const listar = async (req,res) => { try { const busqueda=h.normalizarTexto(req.query.q).slice(0,100), estado=h.normalizarTexto(req.query.estado), activo=h.obtenerEstado(estado), solicitada=h.obtenerPagina(req.query.pagina), filtros={busqueda,activo}; const total=await modelo.contarFiltradas(filtros); const url=pagina=>{const p=new URLSearchParams();if(busqueda)p.set('q',busqueda);if(typeof activo==='boolean')p.set('estado',estado);p.set('pagina',pagina);return `/admin/ciclos-escolares?${p}`}; const paginacion=h.crearPaginacion(total,solicitada,url); const ciclos=await modelo.listarPaginado(filtros,h.LIMITE,(paginacion.paginaActual-1)*h.LIMITE); return res.render('admin/ciclos-escolares/index',{title:'Ciclos escolares | COBAEM 30',menuItems:h.menuCalendario(),ciclos,filtros:{q:busqueda,estado:typeof activo==='boolean'?estado:''},paginacion,mensaje:req.query.creado==='1'?'Ciclo escolar registrado correctamente.':req.query.actualizado==='1'?'Ciclo escolar actualizado correctamente.':req.query.estado==='activado'?'Ciclo escolar activado correctamente.':req.query.estado==='desactivado'?'Ciclo escolar desactivado correctamente.':null}); } catch{return h.mensajeMysql(res,'No fue posible cargar los ciclos escolares.');} };
 const mostrarNueva=(req,res)=>render(res,'nuevo');
 const crear=async(req,res)=>{const d=obtenerDatos(req.body),error=validarDatos(d);if(error)return render(res,'nuevo',{status:422,error,datos:d});try{if(await modelo.buscarDuplicadoClave(d.clave))return render(res,'nuevo',{status:422,error:'La clave ya está registrada.',datos:d});await modelo.crear(d);return res.redirect('/admin/ciclos-escolares?creado=1');}catch(e){if(h.esDuplicado(e))return render(res,'nuevo',{status:422,error:'La clave ya está registrada.',datos:d});return h.mensajeMysql(res,'No fue posible registrar el ciclo escolar.');}};
 const mostrarEditar=async(req,res)=>{const id=h.obtenerId(req.params.id);if(!id)return res.status(404).send('Ciclo escolar no encontrado.');try{const c=await modelo.buscarPorId(id);if(!c)return res.status(404).send('Ciclo escolar no encontrado.');return render(res,'editar',{datos:{id,clave:c.clave,nombre:c.nombre,fechaInicio:String(c.fecha_inicio).slice(0,10),fechaFin:String(c.fecha_fin).slice(0,10)}});}catch{return h.mensajeMysql(res,'No fue posible cargar el ciclo escolar.');}};
 const actualizar=async(req,res)=>{const id=h.obtenerId(req.params.id);if(!id)return res.status(404).send('Ciclo escolar no encontrado.');const d=obtenerDatos(req.body),error=validarDatos(d),vista={id,...d};if(error)return render(res,'editar',{status:422,error,datos:vista});try{if(!await modelo.buscarPorId(id))return res.status(404).send('Ciclo escolar no encontrado.');if(await modelo.buscarDuplicadoClave(d.clave,id))return render(res,'editar',{status:422,error:'La clave ya está registrada.',datos:vista});if(await modelo.contarPeriodosFueraDeRango(id,d.fechaInicio,d.fechaFin)>0)return res.status(409).send('Las nuevas fechas dejarían periodos académicos fuera del ciclo.');const r=await modelo.actualizar(id,d);return r.affectedRows===1?res.redirect('/admin/ciclos-escolares?actualizado=1'):res.status(404).send('Ciclo escolar no encontrado.');}catch(e){if(h.esDuplicado(e))return render(res,'editar',{status:422,error:'La clave ya está registrada.',datos:vista});return h.mensajeMysql(res,'No fue posible actualizar el ciclo escolar.');}};
 const mostrarEstado=async(req,res)=>{const id=h.obtenerId(req.params.id);if(!id)return res.status(404).send('Ciclo escolar no encontrado.');try{const ciclo=await modelo.buscarPorId(id);if(!ciclo)return res.status(404).send('Ciclo escolar no encontrado.');return res.render('admin/ciclos-escolares/estado',{title:'Estado del ciclo escolar | COBAEM 30',menuItems:h.menuCalendario(),ciclo,accion:ciclo.activo?'desactivar':'activar'});}catch{return h.mensajeMysql(res,'No fue posible cargar el ciclo escolar.');}};
 const actualizarEstado=async(req,res)=>{const id=h.obtenerId(req.params.id),accion=req.body.accion;if(!id||!['activar','desactivar'].includes(accion))return res.status(422).send('Solicitud no válida.');try{const c=await modelo.buscarPorId(id);if(!c)return res.status(404).send('Ciclo escolar no encontrado.');const activo=accion==='activar';if(Boolean(c.activo)!==activo){const r=activo?await modelo.actualizarEstado(id,true):await modelo.desactivarSiSinPeriodosActivos(id);if(r.affectedRows!==1)return res.status(409).send('No es posible desactivar un ciclo con periodos académicos activos.');}return res.redirect(`/admin/ciclos-escolares?estado=${activo?'activado':'desactivado'}`);}catch{return h.mensajeMysql(res,'No fue posible cambiar el estado del ciclo escolar.');}};
 return{listar,mostrarNueva,crear,mostrarEditar,actualizar,mostrarEstado,actualizarEstado};
};
module.exports={crearControlador,obtenerDatos,validarDatos,...crearControlador()};
