const generacionModel = require('../models/generacionModel');
const h = require('./adminAcademicCalendarShared');

const datosVacios = { anioInicio: '', anioFin: '' };
const obtenerDatos = (body = {}) => ({ anioInicio: h.obtenerAnio(body.anio_inicio), anioFin: h.obtenerAnio(body.anio_fin) });
const datosVista = (body = {}, normalizados = obtenerDatos(body)) => ({ anioInicio: normalizados.anioInicio ?? h.normalizarTexto(body.anio_inicio), anioFin: normalizados.anioFin ?? h.normalizarTexto(body.anio_fin) });
const validarDatos = (datos) => {
    if (!datos.anioInicio || !datos.anioFin) return 'Los años deben contener exactamente cuatro dígitos.';
    if (datos.anioFin <= datos.anioInicio) return 'El año final debe ser posterior al año inicial.';
    return null;
};

const crearControlador = (modelo = generacionModel) => {
    const renderFormulario = (res, vista, opciones = {}) => res.status(opciones.status || 200).render(`admin/generaciones/${vista}`, { title: `${vista === 'nuevo' ? 'Registrar' : 'Editar'} generación | COBAEM 30`, menuItems: h.menuCalendario(), error: opciones.error || null, datos: opciones.datos || datosVacios });
    const listar = async (req, res) => { try {
        const busqueda = h.normalizarTexto(req.query.q).slice(0, 20); const estado = h.normalizarTexto(req.query.estado); const activo = h.obtenerEstado(estado); const solicitada = h.obtenerPagina(req.query.pagina);
        const filtros = { busqueda, activo }; const total = await modelo.contarFiltradas(filtros);
        const url = (pagina) => { const p = new URLSearchParams(); if (busqueda) p.set('q', busqueda); if (typeof activo === 'boolean') p.set('estado', estado); p.set('pagina', pagina); return `/admin/generaciones?${p}`; };
        const paginacion = h.crearPaginacion(total, solicitada, url); const generaciones = await modelo.listarPaginado(filtros, h.LIMITE, (paginacion.paginaActual - 1) * h.LIMITE);
        return res.render('admin/generaciones/index', { title: 'Generaciones | COBAEM 30', menuItems: h.menuCalendario(), generaciones, filtros: { q: busqueda, estado: typeof activo === 'boolean' ? estado : '' }, paginacion, mensaje: req.query.creado === '1' ? 'Generación registrada correctamente.' : req.query.actualizado === '1' ? 'Generación actualizada correctamente.' : req.query.estado === 'activado' ? 'Generación activada correctamente.' : req.query.estado === 'desactivado' ? 'Generación desactivada correctamente.' : null });
    } catch { return h.mensajeMysql(res, 'No fue posible cargar las generaciones.'); } };
    const mostrarNueva = (req, res) => renderFormulario(res, 'nuevo');
    const crear = async (req, res) => { const d = obtenerDatos(req.body); const error = validarDatos(d); const vista = datosVista(req.body, d); if (error) return renderFormulario(res, 'nuevo', { status: 422, error, datos: vista }); try { if (await modelo.buscarDuplicado(d.anioInicio, d.anioFin)) return renderFormulario(res, 'nuevo', { status: 422, error: 'La generación ya está registrada.', datos: vista }); await modelo.crear(d); return res.redirect('/admin/generaciones?creado=1'); } catch (e) { if (h.esDuplicado(e)) return renderFormulario(res, 'nuevo', { status: 422, error: 'La generación ya está registrada.', datos: vista }); return h.mensajeMysql(res, 'No fue posible registrar la generación.'); } };
    const mostrarEditar = async (req, res) => { const id = h.obtenerId(req.params.id); if (!id) return res.status(404).send('Generación no encontrada.'); try { const g = await modelo.buscarPorId(id); if (!g) return res.status(404).send('Generación no encontrada.'); return renderFormulario(res, 'editar', { datos: { id, anioInicio: g.anio_inicio, anioFin: g.anio_fin } }); } catch { return h.mensajeMysql(res, 'No fue posible cargar la generación.'); } };
    const actualizar = async (req, res) => { const id = h.obtenerId(req.params.id); if (!id) return res.status(404).send('Generación no encontrada.'); const d = obtenerDatos(req.body); const vista = { id, ...datosVista(req.body, d) }; const error = validarDatos(d); if (error) return renderFormulario(res, 'editar', { status: 422, error, datos: vista }); try { if (!await modelo.buscarPorId(id)) return res.status(404).send('Generación no encontrada.'); if (await modelo.buscarDuplicado(d.anioInicio, d.anioFin, id)) return renderFormulario(res, 'editar', { status: 422, error: 'La generación ya está registrada.', datos: vista }); const r = await modelo.actualizar(id, d); return r.affectedRows === 1 ? res.redirect('/admin/generaciones?actualizado=1') : res.status(404).send('Generación no encontrada.'); } catch (e) { if (h.esDuplicado(e)) return renderFormulario(res, 'editar', { status: 422, error: 'La generación ya está registrada.', datos: vista }); return h.mensajeMysql(res, 'No fue posible actualizar la generación.'); } };
    const mostrarEstado = async (req, res) => { const id = h.obtenerId(req.params.id); if (!id) return res.status(404).send('Generación no encontrada.'); try { const generacion = await modelo.buscarPorId(id); if (!generacion) return res.status(404).send('Generación no encontrada.'); return res.render('admin/generaciones/estado', { title: 'Estado de generación | COBAEM 30', menuItems: h.menuCalendario(), generacion, accion: generacion.activo ? 'desactivar' : 'activar' }); } catch { return h.mensajeMysql(res, 'No fue posible cargar la generación.'); } };
    const actualizarEstado = async (req, res) => { const id = h.obtenerId(req.params.id); const accion = req.body.accion; if (!id || !['activar', 'desactivar'].includes(accion)) return res.status(422).send('Solicitud no válida.'); try { const g = await modelo.buscarPorId(id); if (!g) return res.status(404).send('Generación no encontrada.'); const activo = accion === 'activar'; if (Boolean(g.activo) !== activo) { const r = activo ? await modelo.actualizarEstado(id, true) : await modelo.desactivarSiSinGruposActivos(id); if (r.affectedRows !== 1) return res.status(409).send('No es posible desactivar una generación vinculada con grupos activos.'); } return res.redirect(`/admin/generaciones?estado=${activo ? 'activado' : 'desactivado'}`); } catch { return h.mensajeMysql(res, 'No fue posible cambiar el estado de la generación.'); } };
    return { listar, mostrarNueva, crear, mostrarEditar, actualizar, mostrarEstado, actualizarEstado };
};
module.exports = { crearControlador, obtenerDatos, validarDatos, ...crearControlador() };
